language: node_js
node_js:
- 7
deploy:
  provider: gae
  project: is-sensores-uex
  keyfile: gae.json
  verbosity: debug
  on: master
before_install:
- openssl aes-256-cbc -K $encrypted_870ca80e8b63_key -iv $encrypted_870ca80e8b63_iv
  -in gae.json.enc -out gae.json -d
